spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: SeatsAllocation
  config:
    import: configserver:http://localhost:8084/
    
  application:
    name: WEBCHECKIN-SERVICE
      
server:
  port: 8086