server:
  port: 8084
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ShreyashLamkane/FlightManagementSystem
          skipSslValidation: true
  application:
    name: EXTERNAL-CONFIG