server:
  port: 8085
  servlet:
   context-path: /
  
openapi:
 service:
   title: API Gateway doc #title that you will want to display in the swagger ui
   url: http://localhost:8085 #api gateway url
   
spring:
  cloud:
    discovery:
      enabled: true
      
    gateway:
      discovery:
        locator:
          enabled: true
      
      routes:
        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**,/passengers/**
          filters:
            - AuthenticationFilter
          
        - id: FLIGHT-SERVICE
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/details/**
          filters:
            - AuthenticationFilter
            
            
        - id: SEARCH-SERVICE
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**  
          filters:
            - AuthenticationFilter
            
              
        - id: SEATNFARE-SERVICE
          uri: lb://SEATNFARE-SERVICE
          predicates:
            - Path=/seats/**  
          filters:
            - AuthenticationFilter  
            
            
        - id: WEBCHECKIN-SERVICE
          uri: lb://WEBCHECKIN-SERVICE
          predicates:
            - Path=/web/**
          filters:
            - AuthenticationFilter
          
            
        - id: FLIGHT-SECURITY
          uri: lb://FLIGHT-SECURITY
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
            
        - id: RAZORPAY-SERVICE
          uri: lb://RAZORPAY-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
            
  config:
     import: configserver:http://localhost:8084/
    
  application:
    name: FLIGHT-GATEWAY