server:
  port: 8085
spring:
  cloud:
    discovery:
      enabled: true
      
    gateway:
      discovery:
        locator:
          enabled: true
      
      routes:
        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/bookings/**,/passengers/**

        - id: FLIGHT-SERVICE
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/details/**

        - id: SEARCH-SERVICE
          uri: lb://SEARCH-SERVICE
          predicates:
            - Path=/search/**  
            
        - id: SEATNFARE-SERVICE
          uri: lb://SEATNFARE-SERVICE
          predicates:
            - Path=/seats/**  
            
        - id: WEBCHECKIN-SERVICE
          uri: lb://WEBCHECKIN-SERVICE
          predicates:
            - Path=/web/**
  config:
     import: configserver:http://localhost:8084/
    
  application:
    name: FLIGHT-GATEWAY